name: Build ,Test and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 31.97.55.52
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/StoreShop
            git pull
            docker compose -f docker-compose.prod.yml up -d --build